###
GET http://localhost:3003/api/blogs

###
GET http://localhost:3003/api/blogs/679b4d8f27d1017eb7edbc22

###
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvaG5kb2UiLCJpZCI6IjY3YTMzYzA4MjFiYTQxMzc0N2E3ZTg3MiIsImlhdCI6MTczODc1MTAxMH0.GMzlGuoGS3D4mvt5KY6fCYoNGEZCaDr8-KC2kOEhyKc

{
    "author": "John Doe",
    "title": "Created by John Doe",
    "url": "https://www.example.com",
    "likes": 0
}

###
DELETE http://localhost:3003/api/blogs/679b71583c80d67014239916

###
PUT http://localhost:3003/api/blogs/679b4d8f27d1017eb7edbc22
Content-Type: application/json

{
    "title": "Hello, World!",
    "author": "John Doe",
    "url": "https://www.example.com",
    "likes": 0
}